name: Release build

on:
  push:
    branches:
      - release-candidate
  pull_request:
    branches:
      - release-candidate

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for publication-request.json
        id: checkfile
        run: |
          if [[ -f "publication-request.json" ]]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Use Reusable Workflow
        if: steps.checkfile.outputs.exists == 'true'
        uses: DigitalSQR/smart-releases/.github/workflows/release.yaml@main
